spring:
  application:
    name: song-service
  datasource:
    password: root
    username: postgres
    url: jdbc:postgresql://song-service-db:5432/songs
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
