spring:
  application:
    name: song-service
  datasource:
    password: ${SONG_DB_PASSWORD}
    username: ${SONG_DB_USERNAME}
    url: ${SONG_DB_URL}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_DEFAULT_ZONE}
