spring:
  datasource:
    password: root
    username: postgres
    url: jdbc:postgresql://localhost:5432/resources
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
clients:
  song-service: http://localhost:8080
  contextPath: /songs
