spring:
  application:
    name: resource-service
  datasource:
    password: root
    username: postgres
    url: jdbc:postgresql://resource-service-db:5432/resources
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
clients:
  song-service: http://song-service:8080
  contextPath: /songs
