spring:
  application:
    name: resource-service
  datasource:
    password: ${RESOURCE_DB_PASSWORD}
    username: ${RESOURCE_DB_USERNAME}
    url: ${RESOURCE_DB_URL}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
clients:
  song-service: ${SONG_SERVICE_URL}
  contextPath: ${SONG_CONTEXT_PATH}
  s3:
    url: ${LOCALSTACK_URL}
    access_key: ${LOCALSTACK_ACCESS_KEY}
    secret_key: ${LOCALSTACK_SECRET_KEY}
    region: ${LOCALSTACK_REGION}
    bucket_name: ${LOCALSTACK_BUCKET_NAME}
