spring:
  application:
    name: resource-service
  datasource:
    password: ${RESOURCE_DB_PASSWORD}
    username: ${RESOURCE_DB_USERNAME}
    url: ${RESOURCE_DB_URL}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
clients:
  song-service: ${SONG_SERVICE_URL}
  contextPath: ${SONG_CONTEXT_PATH}
